/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package engenharia.de.software;

import Bean.Livro;
import Controle.Conexao;
import DAO.ModeloTabela;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Tiago Oliveira
 */
public class buscarLivro extends javax.swing.JFrame {

    /**
     * Creates new form buscarLivro
     */
    public buscarLivro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nome_completo1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        nome_completo2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(175, 170, 170)));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar Pelo Nome");

        jLabel5.setText("Buscar Pelo Ano");

        nome_completo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_completo1ActionPerformed(evt);
            }
        });

        jButton3.setText("Mostrar Todos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        nome_completo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_completo2ActionPerformed(evt);
            }
        });

        jButton4.setText("Voltar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(nome_completo2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(nome_completo1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome_completo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButton2)
                    .addComponent(nome_completo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            Livro l = new Livro();
            BuscarNomeLivro("_titulo", l.getTitulo());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            Livro l = new Livro();
            BuscarAnoLivro("_ano", l.getAno()); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nome_completo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_completo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_completo1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nome_completo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_completo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_completo2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        telaPrincipal b = new telaPrincipal();
        b.setVisible(true);
        b.setLocationRelativeTo(null);
        b.setSize(800, 600);

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new buscarLivro().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nome_completo1;
    private javax.swing.JTextField nome_completo2;
    // End of variables declaration//GEN-END:variables

    private void BuscarNomeLivro(String busca, String titulo) {
        ResultSet rs = null;
        Connection con = Conexao.getConnection();
        PreparedStatement stmt = null;
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Titulo", "Autor", "Genero", "Ano", "Valor"};
        
        int cont = 0;
        try {
            //select pessoa.nome_completo from (select aluno.Id_pessoaFK as id from (select * from academia where academia.nome_academia="Academia Sol") as acad inner join aluno on aluno.Id_academiaFK = acad.Id_academia) as alu inner join pessoa on pessoa.Id_pessoa = alu.id;
            stmt = con.prepareStatement("SELECT * FROM livro WHERE "+busca+"");
            rs = stmt.executeQuery();
            
            while(rs.next()){
                dados.add(new Object[]{rs.getString("_titulo"), rs.getString("_autor"), rs.getString("_genero"), rs.getInt("_ano"), rs.getString("_valor")});
                cont++;
            }
                
            if(cont == 0){
                JOptionPane.showMessageDialog(null, "Não Foram Encontrados Registros Para:  "+ busca);
            }else{
            
                ModeloTabela modelo = new ModeloTabela(dados, Colunas);

                table.setModel(modelo);

                table.getColumnModel().getColumn(0).setPreferredWidth(216);
                table.getColumnModel().getColumn(0).setResizable(false);

                table.getColumnModel().getColumn(1).setPreferredWidth(216);
                table.getColumnModel().getColumn(1).setResizable(false);

                table.getColumnModel().getColumn(2).setPreferredWidth(155);
                table.getColumnModel().getColumn(2).setResizable(false);

                table.getColumnModel().getColumn(3).setPreferredWidth(150);
                table.getColumnModel().getColumn(3).setResizable(false);

                table.getColumnModel().getColumn(4).setPreferredWidth(150);
                table.getColumnModel().getColumn(4).setResizable(false);

                table.getTableHeader().setReorderingAllowed(false);
                table.setAutoResizeMode(table.AUTO_RESIZE_OFF);

                table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(buscarLivro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void BuscarAnoLivro(String busca, String ano) {
        ResultSet rs = null;
        Connection con = Conexao.getConnection();
        PreparedStatement stmt = null;
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Titulo", "Autor", "Genero", "Ano", "Valor"};
        String nomeac = null;
        int cont = 0;
        try {
            
            stmt = con.prepareStatement("SELECT * FROM clientes WHERE "+busca+"");
            rs = stmt.executeQuery();
            
            
            while(rs.next()){
                dados.add(new Object[]{rs.getString("_titulo"), rs.getString("_autor"), rs.getString("_genero"), rs.getInt("_ano"), rs.getString("_valor")});
                cont++;
            }
                
            if(cont == 0){
                JOptionPane.showMessageDialog(null, "Não Foram Encontrados Registros Para:  "+ busca);
            }else{
                
                ModeloTabela modelo = new ModeloTabela(dados, Colunas);

                table.setModel(modelo);

                table.getColumnModel().getColumn(0).setPreferredWidth(216);
                table.getColumnModel().getColumn(0).setResizable(false);

                table.getColumnModel().getColumn(1).setPreferredWidth(216);
                table.getColumnModel().getColumn(1).setResizable(false);

                table.getColumnModel().getColumn(2).setPreferredWidth(155);
                table.getColumnModel().getColumn(2).setResizable(false);

                table.getColumnModel().getColumn(3).setPreferredWidth(150);
                table.getColumnModel().getColumn(3).setResizable(false);

                table.getColumnModel().getColumn(4).setPreferredWidth(150);
                table.getColumnModel().getColumn(4).setResizable(false);

                table.getTableHeader().setReorderingAllowed(false);
                table.setAutoResizeMode(table.AUTO_RESIZE_OFF);

                table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(buscarLivro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
